### ISSUE TITLE
反馈小问题

### ISSUE THREAD

**Issue by Jaanai-AAM** [Salt-lovely/saltMCBBS#2]
如果关闭侧边栏功能的话，每次载入页面时网页会滑动一下
下面有录屏

https://user-images.githubusercontent.com/40891215/105565596-87b69480-5d62-11eb-8d6b-715174c15f91.mp4

**Comment by Salt-lovely** [comment]
感谢反馈OvO
设计如此，滑动的这一下是为了将主体部分向下移动50px（还是30px来着XD），不过确实会影响网页浏览，我去改一改。


Salt is lovely!
Salt


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Salt-lovely/saltMCBBS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月23日(星期六) 上午10:06
收件人:&nbsp;"Salt-lovely/saltMCBBS"<saltMCBBS@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Salt-lovely/saltMCBBS] 反馈小问题 (#2)





 
如果关闭侧边栏功能的话，每次载入页面时网页会滑动一下
 下面有录屏
 
https://user-images.githubusercontent.com/40891215/105565596-87b69480-5d62-11eb-8d6b-715174c15f91.mp4
